// <auto-generated />
namespace Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreateOrderItemOptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateOrderItemOptions));
        
        string IMigrationMetadata.Id
        {
            get { return "202104280704059_CreateOrderItemOptions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
